"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import type { OperationalSummary } from "@/modules/summary/domain/operational-summary";
import { buildSummaryAlerts } from "@/modules/summary/domain/summary-alerts";
import { buildConciliationBreakdown } from "@/modules/summary/domain/conciliation-breakdown";
import { collectFundingWithdrawal, createFundingWithdrawal, createWalletMovement } from "./summary-actions";
import { AlertDiagnosticChat } from "./alert-diagnostic-chat";

type Props = Readonly<{ accounts: Array<{ id: string; label: string }>; periodId: string; summary: OperationalSummary }>;
const money = (cents: number) => new Intl.NumberFormat("es-AR", { style: "currency", currency: "USD", signDisplay: "auto" }).format(cents / 100);
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "America/Argentina/Buenos_Aires", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const date = (value: string) => new Intl.DateTimeFormat("es-AR", { timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`));
const labels = { external_contribution: "Aporte externo a billetera", personal_withdrawal: "Retiro personal desde billetera", prior_pending_collection: "Cobro pendiente anterior" } as const;
function Card({ label, value, alert = false, featured = false }: { label: string; value: string; alert?: boolean; featured?: boolean }) { return <article className={`progress-card${featured ? " featured" : ""}${alert ? " alert-card" : ""}`}><span>{label}</span><strong>{value}</strong></article>; }

export function ProgressSummary({ accounts, periodId, summary }: Props) {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const alerts = buildSummaryAlerts(summary);
  const conciliation = buildConciliationBreakdown(summary);
  async function wallet(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); const result = await createWalletMovement({ amount: String(form.get("amount") ?? ""), date: String(form.get("date") ?? ""), kind: String(form.get("kind") ?? ""), observation: String(form.get("observation") ?? ""), periodId }); setSaving(false); setMessage(result.message); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  async function withdrawal(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setSaving(true); const result = await createFundingWithdrawal({ accountId: String(form.get("account") ?? ""), amount: String(form.get("amount") ?? ""), approvedOn: String(form.get("approved_on") ?? ""), periodId }); setSaving(false); setMessage(result.message); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  async function collect(id: string) { setSaving(true); const result = await collectFundingWithdrawal({ withdrawalId: id, collectedOn: today(), periodId }); setSaving(false); setMessage(result.message); if (result.ok) router.refresh(); }
  return <section aria-labelledby="progress-summary-title" className="progress-summary-panel" id="resumen">
    <div className="summary-heading"><div><p className="status">RESUMEN OPERATIVO</p><h2 id="progress-summary-title">Capital y conciliación</h2></div><span className="calculated-badge">Calculado automáticamente</span></div>
    <p className="context-note">Cada valor se reconstruye desde Compras, Control Diario, Registro, Billetera y Retiros. No hay saldos editables sin origen.</p>
    <div className="summary-section" aria-live="polite"><h3>Alertas y controles</h3>{alerts.length === 0 ? <p className="summary-clear">No hay diferencias ni datos pendientes detectados en este Resumen.</p> : <div className="summary-alert-list">{alerts.map((alert) => <article className={`summary-alert summary-alert-${alert.severity}`} key={alert.code}><div className="summary-alert-copy"><strong>{alert.title}</strong><p>{alert.detail}</p></div><a href={alert.href}>Revisar</a><AlertDiagnosticChat alertCode={alert.code} periodId={periodId} /></article>)}</div>}</div>
    <Block title="Situación actual"><Card featured label="Saldo broker" value={summary.brokerBalanceInCents === null ? "Sin saldo informado" : money(summary.brokerBalanceInCents)} /><Card label="Saldo billetera" value={money(summary.walletBalanceInCents)} /><Card label="Retiros pendientes" value={money(summary.fundingPendingInCents)} /><Card featured label="Posición observable" value={money(summary.positionObservableInCents)} /></Block>
    <Block title="Capital y resultado"><Card label="Capital neto aportado" value={money(summary.capitalNetInCents)} /><Card featured label="Resultado del período" value={money(summary.periodResultInCents)} /><Card featured label="Posición esperada" value={money(summary.positionExpectedInCents)} /><Card label="Diferencia de capital" value={money(summary.positionDifferenceInCents)} alert={summary.positionDifferenceInCents !== 0} /></Block>
    <div className="summary-section"><h3>Desglose de conciliaciones</h3><p className="context-note">Los importes se recalculan desde sus registros de origen. Una diferencia no se corrige sola.</p><div className="conciliation-grid"><ConciliationCard title="Conciliación de capital" leftTitle="Posición observable" leftLines={conciliation.capital.observable} leftTotal={summary.positionObservableInCents} rightTitle="Posición esperada" rightLines={conciliation.capital.expected} rightTotal={summary.positionExpectedInCents} difference={conciliation.capital.differenceInCents} /><ConciliationCard title="Conciliación de ganancias" leftTitle="Ganancia de cuentas cerradas" leftLines={[]} leftTotal={conciliation.gains.closedInCents} rightTitle="Ganancia reconstruida" rightLines={conciliation.gains.reconstructed} rightTotal={summary.realizedGainInCents - conciliation.gains.differenceInCents} difference={conciliation.gains.differenceInCents} /></div></div>
    <div className="summary-section"><h3>Estado operativo, ganancia y comisión</h3><div className="progress-detail-grid"><article className="progress-detail"><dl><div><dt>Cuentas vírgenes</dt><dd>{summary.accountStates.virgin}</dd></div><div><dt>Cuentas vivas</dt><dd>{summary.accountStates.live}</dd></div><div><dt>Cuentas cerradas</dt><dd>{summary.accountStates.closed}</dd></div><div><dt>Flotante de cobertura</dt><dd>{money(summary.floatingInCents)}</dd></div></dl></article><article className="progress-detail"><dl><div><dt>Ganancia realizada</dt><dd>{money(summary.realizedGainInCents)}</dd></div><div><dt>Ganancia conciliada</dt><dd>{money(summary.periodResultInCents + summary.floatingInCents + summary.virginPriceInCents)}</dd></div><div><dt>Diferencia de ganancias</dt><dd>{money(summary.realizedReconciliationDifferenceInCents)}</dd></div><div><dt>Precio cuentas vírgenes</dt><dd>{money(summary.virginPriceInCents)}</dd></div><div><dt>Comisión mesa ({summary.commissionRateLabel})</dt><dd>{money(summary.commissionInCents)}</dd></div><div><dt>Ganancia trader estimada</dt><dd>{money(summary.traderGainInCents)}</dd></div></dl></article></div></div>
    <div className="summary-section summary-forms"><div><h3>Movimientos de billetera</h3><form className="summary-form" onSubmit={wallet}><input defaultValue={today()} name="date" type="date" required /><select defaultValue="external_contribution" name="kind">{Object.entries(labels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><input inputMode="decimal" name="amount" placeholder="Importe USD" required /><input name="observation" placeholder="Observación (opcional)" /><button disabled={saving}>Guardar movimiento</button></form><div className="summary-list">{summary.walletMovements.length === 0 ? <p>Sin movimientos externos de billetera.</p> : summary.walletMovements.map((movement)=><p key={movement.id}><strong>{date(movement.occurredOn)}</strong> · {labels[movement.kind]} · {money(movement.amountInCents)}</p>)}</div></div><div><h3>Retiros de fondeo</h3><form className="summary-form" onSubmit={withdrawal}><select name="account" required defaultValue=""><option disabled value="">Cuenta</option>{accounts.map((account)=><option key={account.id} value={account.id}>{account.label}</option>)}</select><input defaultValue={today()} name="approved_on" type="date" required /><input inputMode="decimal" name="amount" placeholder="Importe aprobado" required /><button disabled={saving}>Registrar aprobado</button></form><div className="summary-list">{summary.fundingWithdrawals.length === 0 ? <p>Sin retiros de fondeo registrados.</p> : summary.fundingWithdrawals.map((item)=><p key={item.id}><strong>{date(item.approvedOn)}</strong> · {money(item.amountInCents)} · {item.collectedOn ? `Cobrado el ${date(item.collectedOn)}` : <button className="text-action" disabled={saving} onClick={()=>collect(item.id)} type="button">Confirmar cobro</button>}</p>)}</div></div></div>{message && <p className="register-feedback">{message}</p>}
  </section>;
}
function Block({ children, title }: { children: React.ReactNode; title: string }) { return <div className="summary-section"><h3>{title}</h3><div className="progress-primary-grid">{children}</div></div>; }
function ConciliationCard({ difference, leftLines, leftTitle, leftTotal, rightLines, rightTitle, rightTotal, title }: { difference: number; leftLines: Array<{ href: string; label: string; valueInCents: number | null }>; leftTitle: string; leftTotal: number; rightLines: Array<{ href: string; label: string; valueInCents: number | null }>; rightTitle: string; rightTotal: number; title: string }) { return <article className="conciliation-card"><h4>{title}</h4><div className="conciliation-sides"><ConciliationSide title={leftTitle} lines={leftLines} total={leftTotal} /><ConciliationSide title={rightTitle} lines={rightLines} total={rightTotal} /></div><p className={`conciliation-difference${difference !== 0 ? " has-difference" : ""}`}><span>Diferencia</span><strong>{money(difference)}</strong></p></article>; }
function ConciliationSide({ lines, title, total }: { lines: Array<{ href: string; label: string; valueInCents: number | null }>; title: string; total: number }) { return <div className="conciliation-side"><strong>{title}</strong>{lines.length === 0 ? <p className="conciliation-single-total">Total calculado desde cuentas cerradas.</p> : lines.map((line) => <p key={line.label}><a href={line.href}>{line.label}</a><span>{line.valueInCents === null ? "Sin saldo informado" : money(line.valueInCents)}</span></p>)}<footer><span>Total</span><strong>{money(total)}</strong></footer></div>; }
