import { requireNodalAdmin } from "@/modules/admin/server/admin-access";
import { authorizeAndProvisionStudent, reviewDirectAccessRequest, reviewUserInvitation, revokeStudent } from "../user-actions";
import { accountingPeriodMonthAt } from "@/modules/accounting/domain/period-calendar";

type Props = { searchParams: Promise<{ result?: string | string[] }> };
const one = (value: string | string[] | undefined) => typeof value === "string" ? value : undefined;
const messages: Record<string, string> = {
  access_request_approved: "Solicitud aprobada. El usuario quedó preparado en la Mesa Principal.", access_request_rejected: "Solicitud rechazada con trazabilidad.", access_request_review_failed: "No se pudo resolver la solicitud.", authorized: "Usuario autorizado y espacios Real y Práctica preparados.", invalid: "Completá correo, período y motivo.", invalid_access_request: "Revisá los datos de la solicitud.", invalid_invitation: "Revisá los datos de la invitación.", invitation_approved: "Invitación aprobada y usuario preparado.", invitation_rejected: "Invitación rechazada con trazabilidad.", invitation_review_failed: "No se pudo resolver la invitación. Para aprobarla, la persona debe haber iniciado sesión con Google primero.", not_authorized: "No se pudo autorizar. La persona debe haber iniciado sesión con Google primero.", not_revoked: "No se pudo revocar este acceso.", revoked: "Acceso del usuario revocado. Sus registros se conservan.",
};

export default async function AdminUsersPage({ searchParams }: Props) {
  const supabase = await requireNodalAdmin();
  const { result } = await searchParams;
  const [{ data: users }, { data: workspaces }, { data: invitations }] = await Promise.all([
    supabase.from("nodal_users").select("id, email, display_name, access_state, access_role, authorized_at, revoked_at, created_at").order("created_at", { ascending: false }),
    supabase.from("workspaces").select("owner_user_id, modality, periods(id)"),
    supabase.from("nodal_user_invitations")
      .select("id,recipient_email,status,created_at,referred_by_user_id")
      .in("status", ["sent", "pending_approval"]).order("created_at", { ascending: false }),
  ]);
  const pendingUsers = (users ?? []).filter((user) => user.access_state === "pending");
  const currentUsers = (users ?? []).filter((user) => user.access_state === "active");
  const revokedUsers = (users ?? []).filter((user) => user.access_state === "revoked");
  const workspaceCount = new Map((workspaces ?? []).map((workspace) => [workspace.owner_user_id, workspace.periods.length]));
  return <div className="admin-page admin-shell">
    <header className="workspace-view-heading admin-page-heading"><div><p className="status">ACCESOS</p><h2>Usuarios</h2></div><p>Altas, bajas y espacios habilitados.</p></header>
    {one(result) && messages[one(result)!] && <p className={`admin-result ${["authorized", "revoked", "invitation_approved", "invitation_rejected", "access_request_approved", "access_request_rejected"].includes(one(result)!) ? "success" : "error"}`}>{messages[one(result)!]}</p>}
    <section className="admin-user-list admin-access-requests"><div className="admin-section-heading"><div><p className="status">APROBACIÓN MASTER</p><h3>Solicitudes de apertura</h3></div><span className="calculated-badge">{pendingUsers.length}</span></div>
      {pendingUsers.length === 0 ? <p className="empty-state">No hay solicitudes directas pendientes.</p> : <div>{pendingUsers.map((user) => <article className="admin-user-row" key={user.id}><div><strong>{user.display_name || user.email}</strong><span>{user.email}</span><small>Solicitada {new Intl.DateTimeFormat("es-AR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Argentina/Buenos_Aires" }).format(new Date(user.created_at))}</small></div><form action={reviewDirectAccessRequest} className="admin-invitation-review"><input name="target_user_id" type="hidden" value={user.id} /><input defaultValue={accountingPeriodMonthAt()} name="period_month" type="hidden" /><label>Nombre<input defaultValue={user.display_name || ""} name="display_name" placeholder="Nombre visible" /></label><label>% op. propias<input defaultValue="40" max="100" min="0" name="commission_percent" required step="0.01" type="number" /></label><label>Motivo<input defaultValue="Alta aprobada por Admin Master" name="reason" required /></label><div><button className="primary-action" name="decision" type="submit" value="approve">Aprobar</button><button className="admin-revoke" name="decision" type="submit" value="reject">Rechazar</button></div></form></article>)}</div>}
    </section>
    <section className="admin-user-grid">
      <article className="admin-user-form"><p className="status">NUEVO ACCESO</p><h2>Autorizar usuario</h2><form action={authorizeAndProvisionStudent}><label>Correo de Google<input name="email" placeholder="usuario@gmail.com" required type="email" /></label><label>Nombre (opcional)<input name="display_name" placeholder="Nombre del usuario" /></label><label>Primer período<input defaultValue={accountingPeriodMonthAt()} name="period_month" required type="date" /></label><label>Motivo<input defaultValue="Alta de usuario" name="reason" required /></label><button className="primary-action" type="submit">Autorizar y preparar espacios</button></form></article>
      <article className="admin-user-list"><div className="admin-section-heading"><div><p className="status">ACCESOS ACTUALES</p><h3>Usuarios NODAL</h3></div><span className="calculated-badge">{currentUsers.length}</span></div>{currentUsers.length === 0 ? <p className="empty-state">Todavía no hay usuarios autorizados.</p> : <div>{currentUsers.map((user) => <article className="admin-user-row" key={user.id}><div><strong>{user.display_name || user.email}</strong><span>{user.email}</span><small>{user.access_role === "admin" ? "Administrador" : workspaceCount.has(user.id) ? `${workspaceCount.get(user.id)} períodos preparados` : "Sin espacios preparados"}</small></div><div><span className={`admin-state ${user.access_state === "active" ? "active_today" : "inactive"}`}>{user.access_state === "active" ? "Habilitado" : "Revocado"}</span>{user.access_role === "student" && user.access_state === "active" && <form action={revokeStudent}><input name="target_user_id" type="hidden" value={user.id} /><input aria-label={`Motivo de baja de ${user.email}`} defaultValue="Baja de acceso" name="reason" required /><button className="admin-revoke" type="submit">Revocar</button></form>}</div></article>)}</div>}</article>
    </section>
    {revokedUsers.length > 0 && <details className="admin-user-list admin-revoked-history"><summary>Historial de accesos revocados · {revokedUsers.length}</summary><div>{revokedUsers.map((user) => <article className="admin-user-row" key={user.id}><div><strong>{user.display_name || user.email}</strong><span>{user.email}</span><small>El perfil y sus registros se conservan.</small></div><span className="admin-state inactive">Revocado</span></article>)}</div></details>}
    <section className="admin-user-list"><div className="admin-section-heading"><div><p className="status">APROBACIÓN MASTER</p><h3>Invitaciones pendientes</h3></div><span className="calculated-badge">{(invitations ?? []).length}</span></div>
      {(invitations ?? []).length === 0 ? <p className="empty-state">No hay invitaciones pendientes.</p> : <div>{(invitations ?? []).map((invitation) => {
        const referrer = (users ?? []).find((user) => user.id === invitation.referred_by_user_id);
        return <article className="admin-user-row" key={invitation.id}><div><strong>{invitation.recipient_email}</strong><span>Invitado por {referrer?.display_name || referrer?.email || "usuario de mesa"}</span><small>Debe ingresar con Google antes de la aprobación.</small></div><form action={reviewUserInvitation} className="admin-invitation-review"><input name="invitation_id" type="hidden" value={invitation.id} /><input defaultValue={accountingPeriodMonthAt()} name="period_month" type="hidden" /><label>Nombre<input name="display_name" placeholder="Nombre visible" /></label><label>% op. propias<input defaultValue="40" max="100" min="0" name="commission_percent" required step="0.01" type="number" /></label><label>Motivo<input defaultValue="Alta aprobada por Admin Master" name="reason" required /></label><div><button className="primary-action" name="decision" type="submit" value="approve">Aprobar</button><button className="admin-revoke" name="decision" type="submit" value="reject">Rechazar</button></div></form></article>;
      })}</div>}
    </section>
  </div>;
}
